### ISSUE TITLE
Error linking module

### ISSUE THREAD

**Issue by louisdauvois** [georgipeltekov/ngx-file-drop#28]
Hi,

First of all thanks you.

I'm trying to implement your module but : 
```
frontend     | WARNING in ./node_modules/ngx-file-drop/node_modules/@angular/core/esm5/core.js
frontend     | 6438:15-36 Critical dependency: the request of a dependency is an expression
frontend     |     at ImportLazyContextDependency.getWarnings (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
frontend     |     at Compilation.reportDependencyErrorsAndWarnings (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:677:24)
frontend     |     at Compilation.finish (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:535:9)
frontend     |     at applyPluginsParallel.err (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compiler.js:512:17)
frontend     |     at /src/app/node_modules/tapable/lib/Tapable.js:289:11
frontend     |     at _addModuleChain (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:481:11)
frontend     |     at processModuleDependencies.err (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:452:13)
frontend     |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
frontend     |     at process._tickCallback (internal/process/next_tick.js:180:9)
frontend     | 
frontend     | WARNING in ./node_modules/ngx-file-drop/node_modules/@angular/core/esm5/core.js
frontend     | 6458:15-102 Critical dependency: the request of a dependency is an expression
frontend     |     at ImportLazyContextDependency.getWarnings (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/dependencies/ImportContextDependency.js:28:4)
frontend     |     at Compilation.reportDependencyErrorsAndWarnings (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:677:24)
frontend     |     at Compilation.finish (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:535:9)
frontend     |     at applyPluginsParallel.err (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compiler.js:512:17)
frontend     |     at /src/app/node_modules/tapable/lib/Tapable.js:289:11
frontend     |     at _addModuleChain (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:481:11)
frontend     |     at processModuleDependencies.err (/src/app/node_modules/@angular/cli/node_modules/webpack/lib/Compilation.js:452:13)
frontend     |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
frontend     |     at process._tickCallback (internal/process/next_tick.js:180:9)
frontend     |                           
```

```
client?d28c:43 ./node_modules/ngx-file-drop/node_modules/@angular/core/esm5/core.js
6438:15-36 Critical dependency: the request of a dependency is an expression
```

```
Unexpected value 'FileDropModule' imported by the module 'AppModule'. Please add a @NgModule annotation. 
```

Package.json 
```
{
    "name": "project",
    "version": "0.0.0",
    "license": "MIT",
    "scripts": {
        "ng": "ng",
        "start": "ng serve -H 0.0.0.0 -port 4903 --disable-host-check",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^4.4.6",
        "@angular/cdk": "^2.0.0-beta.12",
        "@angular/common": "^4.4.6",
        "@angular/compiler": "^4.4.6",
        "@angular/core": "^4.4.6",
        "@angular/flex-layout": "^2.0.0-beta.10-4905443",
        "@angular/forms": "^4.4.6",
        "@angular/http": "^4.4.6",
        "@angular/material": "^2.0.0-beta.12",
        "@angular/platform-browser": "^4.4.6",
        "@angular/platform-browser-dynamic": "^4.4.6",
        "@angular/router": "^4.4.6",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
        "@ngx-translate/core": "^8.0.0",
        "@types/jstree": "^3.3.35",
        "@types/toastr": "^2.1.35",
        "angular-oauth2-oidc": "^2.1.8",
        "animate.css": "^3.5.2",
        "bootstrap": "^3.3.7",
        "chart.js": "^2.7.1",
        "core-js": "^2.5.1",
        "crypto-js": "^3.1.9-1",
        "enhanced-resolve": "^3.4.1",
        "font-awesome": "^4.7.0",
        "hammerjs": "^2.0.8",
        "jquery": "^3.2.1",
        "jquery-slimscroll": "^1.3.8",
        "jquery-sparkline": "^2.4.0",
        "jstree": "^3.3.4",
        "jvectormap": "^1.2.2",
        "metismenu": "^2.7.1",
        "ngx-bootstrap": "^2.0.0-beta.8",
        "ngx-file-drop": "^2.0.1",
        "peity": "^3.2.1",
        "rxjs": "^5.5.2",
        "simplebar": "^2.5.0",
        "snazzy-info-window": "^1.1.0",
        "toastr": "^2.1.2",
        "webpack": "^3.8.1",
        "zone.js": "^0.8.18"
    },
    "devDependencies": {
        "@angular/cli": "1.3.1",
        "@angular/compiler-cli": "^4.4.6",
        "@angular/language-service": "^4.4.6",
        "@types/googlemaps": "^3.29.1",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "^6.0.90",
        "codelyzer": "~3.1.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "node-sass": "^4.6.0",
        "protractor": "~5.1.2",
        "raw-loader": "^0.5.1",
        "sass-loader": "^6.0.6",
        "ts-node": "~3.2.0",
        "tslint": "~5.3.2",
        "typescript": "~2.3.3"
    }
}
```

appmodule 
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {Http, HttpModule} from '@angular/http';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { LocationStrategy, HashLocationStrategy, PathLocationStrategy } from '@angular/common';

import { ROUTES } from './app.routes';
import { AppComponent } from './app.component';

// App views
import {AppviewsModule} from './_views/appviews.module';

// App modules/components
import {LayoutsModule} from './_components/common/layouts/layouts.module';

import {HttpClientModule} from '@angular/common/http';
import {AuthGuard} from './_guards/auth.guard';

import {OAuthService, UrlHelperService} from 'angular-oauth2-oidc';
import {SecurityService} from './_services/security.service';

import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {ItConstellationModule} from './_views/it-constellation/it-constellation.module';
import { FileDropModule } from 'ngx-file-drop';
@NgModule({
    declarations: [
        AppComponent,

    ],
    imports: [
        BrowserModule,
        FormsModule,
        CommonModule,
        HttpModule,
        LayoutsModule,
        ItConstellationModule,
        AppviewsModule,
        HttpClientModule,
      FileDropModule,
      RouterModule.forRoot(ROUTES),
        BrowserAnimationsModule
        /*RouterModule.forRoot(ROUTES, {
            enableTracing: /localhost/.test(document.location.host)
        })*/
    ],
    providers: [
        {provide: LocationStrategy, useClass: PathLocationStrategy},
        AuthGuard,
        OAuthService,
        UrlHelperService,
        SecurityService
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

Thanks for your help.

**Comment by georgipeltekov** [comment]
Hi,

could you please provide a repo, where the issue can be reproduced?

**Comment by georgipeltekov** [comment]
Also ,can you try to delete your node_modules folder and run npm install after that?

**Comment by louisdauvois** [comment]
I try the node_modules. Not working

**Comment by georgipeltekov** [comment]
could you provide some sources that reproduce the issue?
