### ISSUE TITLE
Metadata version mismatch for module 

### ISSUE THREAD

**Issue by juni381** [georgipeltekov/ngx-file-drop#35]
hello , i am using CookieSevice , first i have installl them by 
npm install ngx-cookie --save 
then i created cookie backend for fake token generating , now i am getting error below :--

Error: Metadata version mismatch for module F:/edcertsWallet/node_modules/ngx-cookie/index.d.ts, found version 4, expected 3, resolving symbol AppModule in F:/edcertsWallet/src/app/app.module.ts, resolving symbol AppModule in F:/edcertsWallet/src/app/app.module.ts, resolving symbol AppModule in F:/edcertsWallet/src/app/app.module.ts
    at syntaxError (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:25111:23)
    at StaticReflector.simplify (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:25123:13)
    at StaticReflector.annotations (F:\edcertsWallet\node_modules\@angular\compiler\bundles\compiler.umd.js:24553:41)
    at _getNgModuleMetadata (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (F:\edcertsWallet\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (F:\edcertsWallet\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (F:\edcertsWallet\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by georgipeltekov** [comment]
This is connected with ngx-cookie, now the ngx-file-drop. You can try to post in their github
